package frame;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class Produk extends javax.swing.JInternalFrame {
    
    private void kosongkan(){
        txtidproduk.setEditable(true);
        txtidproduk.setText(null);
        txtnproduk.setText(null);
        txtjumlahs.setText(null);
        txtharga.setText(null);
    }
    private void tampilkan(){
        DefaultTableModel model=new DefaultTableModel();
        model.addColumn("ID Produk");
        model.addColumn("Nama Produk");
        model.addColumn("Jumlah Stok");
        model.addColumn("Harga Jual");
        
        try{
            String sql="select *from produk";
            java.sql.Connection conn=(Connection)Connect.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
                
            }
            tableproduk.setModel(model);
        }catch(SQLException e){
            System.out.println("Error : "+e.getMessage());
        }
    }

    public Produk() {
        initComponents();
        
        tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableproduk = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtidproduk = new javax.swing.JTextField();
        txtnproduk = new javax.swing.JTextField();
        txtjumlahs = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        tbAdd = new javax.swing.JButton();
        tbEdit = new javax.swing.JButton();
        tbDelete = new javax.swing.JButton();
        tbCancel = new javax.swing.JButton();
        tbSave = new javax.swing.JButton();
        tbExit = new javax.swing.JButton();

        setClosable(true);
        setTitle("Produk");

        jLabel1.setText("Table Produk");

        tableproduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Produk", "Nama Produk", "Jumlah Stok", "Harga Jual"
            }
        ));
        tableproduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableprodukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableproduk);

        jLabel2.setText("ID Produk");

        jLabel3.setText("Nama Produk");

        jLabel4.setText("Jumlah Stok");

        jLabel5.setText("Harga Jual");

        tbAdd.setText("Add");
        tbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbAddActionPerformed(evt);
            }
        });

        tbEdit.setText("Edit");
        tbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbEditActionPerformed(evt);
            }
        });

        tbDelete.setText("Delete");
        tbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDeleteActionPerformed(evt);
            }
        });

        tbCancel.setText("Cancel");
        tbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCancelActionPerformed(evt);
            }
        });

        tbSave.setText("Save");
        tbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSaveActionPerformed(evt);
            }
        });

        tbExit.setText("Exit");
        tbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tbAdd)
                                .addGap(18, 18, 18)
                                .addComponent(tbEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbDelete)
                                .addGap(18, 18, 18)
                                .addComponent(tbCancel)
                                .addGap(18, 18, 18)
                                .addComponent(tbSave))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addComponent(tbExit))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtidproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjumlahs, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtidproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtjumlahs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbAdd)
                            .addComponent(tbEdit)
                            .addComponent(tbDelete)
                            .addComponent(tbCancel)
                            .addComponent(tbSave))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tbExit)))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbAddActionPerformed
        kosongkan();
        txtidproduk.setFocusable(true);
    }//GEN-LAST:event_tbAddActionPerformed

    private void tbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_tbExitActionPerformed

    private void tbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSaveActionPerformed
        try{
        String sql="insert into produk values('"+txtidproduk.getText()+"','"+txtnproduk.getText()+"','"+txtjumlahs.getText()+"','"+txtharga.getText()+"')";
        java.sql.Connection conn=(Connection)Connect.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Data Berhasil Ditambahkan");
            tampilkan();
            kosongkan();
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_tbSaveActionPerformed

    private void tbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDeleteActionPerformed
        try{
            String sql="delete from produk where produk_id='"+txtidproduk.getText()+"'";
            java.sql.Connection conn=(Connection)Connect.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Berhasil Hapus data");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        tampilkan();
        kosongkan();
    }//GEN-LAST:event_tbDeleteActionPerformed

    private void tbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCancelActionPerformed
        kosongkan();
    }//GEN-LAST:event_tbCancelActionPerformed

    private void tableprodukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableprodukMouseClicked
       int baris=tableproduk.rowAtPoint(evt.getPoint());
        String id=tableproduk.getValueAt(baris, 0).toString();
        txtidproduk.setText(id);
        
        String nama=tableproduk.getValueAt(baris, 1).toString();
        txtnproduk.setText(nama);
        
        String jumlah=tableproduk.getValueAt(baris, 2).toString();
        txtjumlahs.setText(jumlah);
        
        String harga=tableproduk.getValueAt(baris, 3).toString();
        txtharga.setText(harga); 
    }//GEN-LAST:event_tableprodukMouseClicked

    private void tbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbEditActionPerformed
        try{
            String sql="update produk set produk_id='"+txtidproduk.getText()+"',nama_produk='"+txtnproduk.getText()+"',jumlah_stok='"+txtjumlahs.getText()+"',harga_jual='"+txtharga.getText()+"' where produk_id='"+txtidproduk.getText()+"'";
            java.sql.Connection conn=(Connection)Connect.configDB();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Berhasil Edit data");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        tampilkan();
        kosongkan();
    }//GEN-LAST:event_tbEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableproduk;
    private javax.swing.JButton tbAdd;
    private javax.swing.JButton tbCancel;
    private javax.swing.JButton tbDelete;
    private javax.swing.JButton tbEdit;
    private javax.swing.JButton tbExit;
    private javax.swing.JButton tbSave;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtidproduk;
    private javax.swing.JTextField txtjumlahs;
    private javax.swing.JTextField txtnproduk;
    // End of variables declaration//GEN-END:variables
}
